#!/bin/bash
# Example script showing how to customize client startup with environment variables

echo "🔧 Multi-Screen Client Configuration Examples"
echo ""

# Example 1: Using .env file (recommended)
echo "📋 Example 1: Using .env file (recommended)"
echo "   1. Copy env.example to .env:"
echo "      cp env.example .env"
echo "   2. Edit .env with your settings:"
echo "      nano .env"
echo "   3. Run the clients:"
echo "      ./start_client1.sh"
echo "      ./start_client2_delayed.sh"
echo ""

# Example 2: Inline environment variables
echo "📋 Example 2: Inline environment variables"
echo "   SERVER_URL=http://192.168.1.200:5000 \\"
echo "   HOSTNAME=OFFICE_MONITOR_1 \\"
echo "   DISPLAY_NAME=\"Office Monitor 1\" \\"
echo "   ./start_client1.sh"
echo ""

# Example 3: Custom monitor assignments
echo "📋 Example 3: Custom monitor assignments"
echo "   MONITOR_INDEX=2 \\"
echo "   MONITOR_LOCATION=\"center\" \\"
echo "   HOSTNAME=CONFERENCE_ROOM \\"
echo "   DISPLAY_NAME=\"Conference Room Display\" \\"
echo "   ./start_client1.sh"
echo ""

# Example 4: Custom startup delay
echo "📋 Example 4: Custom startup delay for Client 2"
echo "   STARTUP_DELAY=60 \\"
echo "   HOSTNAME=DELAYED_CLIENT \\"
echo "   ./start_client2_delayed.sh"
echo ""

echo "💡 Available Environment Variables:"
echo "   Client 1:"
echo "     CLIENT1_SERVER_URL     - Server URL"
echo "     CLIENT1_HOSTNAME       - Client hostname"
echo "     CLIENT1_DISPLAY_NAME   - Display name"
echo "     CLIENT1_MONITOR_INDEX  - Monitor index"
echo "     CLIENT1_MONITOR_LOCATION - Monitor location description"
echo ""
echo "   Client 2:"
echo "     CLIENT2_SERVER_URL     - Server URL"
echo "     CLIENT2_HOSTNAME       - Client hostname"
echo "     CLIENT2_DISPLAY_NAME   - Display name"
echo "     CLIENT2_MONITOR_INDEX  - Monitor index"
echo "     CLIENT2_MONITOR_LOCATION - Monitor location description"
echo "     CLIENT2_STARTUP_DELAY  - Delay before starting (seconds)"
echo ""
echo "📄 .env File Format:"
echo "   CLIENT1_SERVER_URL=http://192.168.1.100:5000"
echo "   CLIENT1_HOSTNAME=UB_3S_1"
echo "   CLIENT1_DISPLAY_NAME=UB_3S_1"
echo "   CLIENT1_MONITOR_INDEX=0"
echo "   CLIENT1_MONITOR_LOCATION=left"
echo "   CLIENT2_SERVER_URL=http://192.168.1.100:5000"
echo "   CLIENT2_HOSTNAME=UB_3S_2"
echo "   CLIENT2_DISPLAY_NAME=UB_3S_2"
echo "   CLIENT2_MONITOR_INDEX=1"
echo "   CLIENT2_MONITOR_LOCATION=right"
echo "   CLIENT2_STARTUP_DELAY=30"
